; PlatformIO project configuration for the LilyGo T-Display S3.
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = t-display-s3

[env:t-display-s3]
platform = platformio/espressif32@^6.9.0
board = lilygo-t-display-s3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    lovyan03/LovyanGFX@^1.2.0
